'use client';

import { useCallback, useEffect, useRef, useState } from 'react';

const SUPPRESS_MS = 900;

/**
 * Keeps the active ayah in view, and gets out of the way when the user scrolls.
 *
 * `wheel` and `touchmove` are direct hardware-input events — `scrollIntoView` never
 * generates them — so they always mean genuine user intent and suspend immediately.
 * A plain `scroll` event, however, IS generated by our own smooth `scrollIntoView`
 * call, so a short suppression window after each programmatic scroll keeps that
 * echo from being misread as the user taking over.
 */
export function useAutoScroll(activeAyah: number, enabled: boolean) {
  const [suspended, setSuspended] = useState(false);
  const suppressUntil = useRef(0);

  useEffect(() => {
    const suspend = () => setSuspended(true);
    const onScroll = () => {
      if (performance.now() < suppressUntil.current) return;
      suspend();
    };
    window.addEventListener('wheel', suspend, { passive: true });
    window.addEventListener('touchmove', suspend, { passive: true });
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => {
      window.removeEventListener('wheel', suspend);
      window.removeEventListener('touchmove', suspend);
      window.removeEventListener('scroll', onScroll);
    };
  }, []);

  useEffect(() => {
    if (!enabled || suspended) return;
    const el = document.querySelector(`[data-ayah="${activeAyah}"]`);
    if (!el) return;
    suppressUntil.current = performance.now() + SUPPRESS_MS;
    el.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, [activeAyah, enabled, suspended]);

  const resume = useCallback(() => {
    setSuspended(false);
    suppressUntil.current = performance.now() + SUPPRESS_MS;
  }, []);

  return { suspended, resume };
}
